public with sharing class CAP_Info_Mock {
    Public Static String getMockAccount (){
    return'{"accountStatus" : "enabled","transactionDetails": {"properties":{"resourceId": "cb880508-78e9-11ea-bc55-0242ac130003","name": "Supermarket","balanceType": "expected","amount":{"currency":"EUR","amount":"5877.78"},"transactionDate": "2020-04-25T15:30:35.035Z"}},"accountTransactionList":[{"iban":"ES4700759339324669344918","amount":{"currency":"EUR","amount":"5877.78"},"currencyCode":"EUR","transactionDate":"2020-04-25T15:30:35.035Z","amountValue":"5877.78","product": "current"}]}';
    }
}
